#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$(cd "$DIR/../../" && pwd)"

# Build _cabana
cd "$ROOT"
scons -j"$(nproc)" tools/cabana/_cabana

# Set Qt plugin path for vendored Qt5
export QT_PLUGIN_PATH="$(python3 -c 'import qt5; print(qt5.DIR)')/plugins"

exec "$DIR/_cabana" "$@"
