import os
import shutil
import subprocess

import imgui
import nanosvg

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal')

# Always build replay_lib (needed by imgui build too)
SConscript(['#tools/replay/SConscript'])
Import('replay_lib')

# ---- Cabana build ----
cabana_env = env.Clone()
cabana_env['CPPPATH'] += [imgui.INCLUDE_DIR, imgui.SRC_DIR, nanosvg.INCLUDE_DIR]
opendbc_path = '-DOPENDBC_FILE_PATH=\'"%s"\'' % (cabana_env.Dir("../../opendbc/dbc").abspath)
cabana_env['CXXFLAGS'] += [opendbc_path, '-DImDrawIdx=unsigned']

if arch != "Darwin":
  cabana_env['CXXFLAGS'] += ['-DIMGUI_IMPL_OPENGL_ES3']
imgui_sources = [
  f'{imgui.SRC_DIR}/imgui.cpp',
  f'{imgui.SRC_DIR}/imgui_draw.cpp',
  f'{imgui.SRC_DIR}/imgui_widgets.cpp',
  f'{imgui.SRC_DIR}/imgui_tables.cpp',
  f'{imgui.SRC_DIR}/implot.cpp',
  f'{imgui.SRC_DIR}/implot_items.cpp',
  f'{imgui.SRC_DIR}/imgui_impl_opengl3.cpp',
]

cabana_srcs = [
  'imgui/settings.cc', 'imgui/commands.cc',
  'imgui/stream.cc', 'imgui/livestream.cc',
  'imgui/replaystream.cc', 'imgui/devicestream.cc',
  'imgui/pandastream.cc',
  'imgui/dbcmanager.cc', 'imgui/dbcfile.cc',
  'imgui/util.cc', 'imgui/export.cc',
  'imgui/bootstrap.cc',
]
if arch != "Darwin":
  cabana_srcs += ['imgui/socketcanstream.cc']

# Shared sources built with unique object names so Cabana outputs do not collide with other workspace targets.
cabana_shared_srcs = {
  'cabana_dbc': 'dbc/dbc.cc',
  'cabana_message_list': 'core/message_list.cc',
  'cabana_persistent_state': 'core/persistent_state.cc',
  'cabana_workspace_state': 'core/workspace_state.cc',
  'cabana_launch_config': 'core/launch_config.cc',
  'cabana_panda': 'panda.cc',
}
cabana_shared_objs = [cabana_env.Object(target=name, source=src) for name, src in cabana_shared_srcs.items()]

cabana_base_libs = [common, messaging, cereal, visionipc, replay_lib,
                    'avformat', 'avcodec', 'swresample', 'avutil',
                    'x264', 'z', 'bz2', 'zstd', 'yuv', 'usb-1.0',
                    'capnp', 'kj',
                    'm', 'ssl', 'crypto', 'pthread']

cabana_backend_lib = cabana_env.Library("cabana_backend_lib", cabana_srcs + cabana_shared_objs, LIBS=cabana_base_libs)
imgui_core_objs = [cabana_env.Object(target='cabana_' + os.path.splitext(os.path.basename(src))[0], source=src) for src in imgui_sources]
imgui_core_lib = cabana_env.Library("cabana_imgui_core_lib", imgui_core_objs, LIBS=cabana_base_libs)

# SDL2 is required for the cabana GUI binary but may not be available on CI.
# Skip building the app binary if SDL2 is not found (matches Qt cabana's guard pattern).
has_sdl2 = False
if arch == "Darwin":
  has_sdl2 = shutil.which('sdl2-config') is not None
else:
  try:
    subprocess.check_call(['pkg-config', '--exists', 'sdl2'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    has_sdl2 = True
  except (subprocess.CalledProcessError, FileNotFoundError):
    pass

if not has_sdl2:
  Return()

cabana_app_env = cabana_env.Clone()
cabana_app_env['LINKFLAGS'].append('-Wl,-strip-debug')
if arch == "Darwin":
  cabana_app_env.ParseConfig('sdl2-config --cflags --libs')
  cabana_frameworks = ['Cocoa', 'IOKit', 'CoreVideo', 'OpenGL']
else:
  cabana_app_env.ParseConfig('pkg-config --cflags --libs sdl2')
  cabana_frameworks = []

cabana_libs = ['SDL2', 'json11', 'jpeg'] + cabana_base_libs
if arch != "Darwin":
  cabana_libs += ['GL', 'dl', 'rt']
  cabana_app_env['LINKFLAGS'] += ['-Wl,--start-group']
  cabana_app_env['_LIBFLAGS'] = cabana_app_env.get('_LIBFLAGS', '') + ' -Wl,--end-group'

cabana_main = cabana_app_env.Object('cabana_main', 'imgui/main.cc')
cabana_app = cabana_app_env.Object('cabana_app', 'imgui/app.cc')
cabana_app_util = cabana_app_env.Object('cabana_app_util', 'imgui/app_util.cc')
cabana_app_panels = cabana_app_env.Object('cabana_app_panels', 'imgui/app_panels.cc')
cabana_app_detail_panels = cabana_app_env.Object('cabana_app_detail_panels', 'imgui/app_detail_panels.cc')
cabana_app_dialogs = cabana_app_env.Object('cabana_app_dialogs', 'imgui/app_dialogs.cc')
cabana_icons = cabana_app_env.Object('cabana_icons', 'imgui/icons.cc')
cabana_app_env.Program('cabana', [cabana_main, cabana_app, cabana_app_util, cabana_app_panels, cabana_app_detail_panels, cabana_app_dialogs, cabana_icons, cabana_backend_lib, imgui_core_lib],
                       LIBS=cabana_libs, FRAMEWORKS=cabana_frameworks)
