import os

import qt5
import libusb

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal')

SConscript(['#tools/replay/SConscript'])
Import('replay_lib')

qt_env = env.Clone()
qt_env['CPPPATH'] += [qt5.INCLUDE_DIR, libusb.INCLUDE_DIR]
qt_env['LIBPATH'] += [qt5.LIB_DIR, libusb.LIB_DIR]
qt_modules = ["Widgets", "Gui", "Core"]

qt_libs = []
if arch == "Darwin":
  qt_dirs = [qt5.INCLUDE_DIR]
  qt_dirs += [os.path.join(qt5.LIB_DIR, f"Qt{m}.framework", "Headers") for m in qt_modules]
  qt_env["CCFLAGS"] += ["-iframework" + qt5.LIB_DIR]
  qt_env["LINKFLAGS"] += ["-F" + qt5.LIB_DIR]
  qt_env["FRAMEWORKS"] += [f"Qt{m}" for m in qt_modules] + ["OpenGL", "CoreFoundation", "IOKit", "Security"]
else:
  qt_dirs = [qt5.INCLUDE_DIR]
  qt_gui_path = os.path.join(qt5.INCLUDE_DIR, "QtGui")
  qt_gui_dirs = [d for d in os.listdir(qt_gui_path) if os.path.isdir(os.path.join(qt_gui_path, d))]
  qt_dirs += [os.path.join(qt5.INCLUDE_DIR, "QtGui", qt_gui_dirs[0], "QtGui")] if qt_gui_dirs else []
  qt_dirs += [os.path.join(qt5.INCLUDE_DIR, f"Qt{m}") for m in qt_modules]
  qt_libs = [f"Qt5{m}" for m in qt_modules] + ["GL"]

qt_env['QTDIR'] = qt5.DIR
qt_env['QT3DIR'] = qt5.DIR
qt_env.AppendENVPath('PATH', qt5.BIN_DIR)
qt_env.Tool('qt3')

qt_env['CPPPATH'] += qt_dirs
qt_flags = [
  "-D_REENTRANT",
  "-DQT_NO_DEBUG",
  "-DQT_WIDGETS_LIB",
  "-DQT_GUI_LIB",
  "-DQT_CORE_LIB",
  "-DQT_MESSAGELOGCONTEXT",
]
qt_env['CXXFLAGS'] += qt_flags
qt_env['LIBPATH'] += ['#selfdrive/ui', ]
qt_env['LIBS'] = qt_libs

if arch != "Darwin":
  qt_env.Append(RPATH=[qt5.LIB_DIR])

base_frameworks = qt_env['FRAMEWORKS']
base_libs = [common, messaging, cereal, visionipc, 'm', 'pthread'] + qt_env["LIBS"]

if arch == "Darwin":
  base_frameworks.append('QtCharts')
else:
  base_libs.append('Qt5Charts')

cabana_env = qt_env.Clone()
cabana_libs = [cereal, messaging, visionipc, replay_lib, 'avformat', 'avcodec', 'swresample', 'avutil', 'x264', 'z', 'bz2', 'zstd', 'yuv', 'usb-1.0'] + base_libs
opendbc_path = '-DOPENDBC_FILE_PATH=\'"%s"\'' % (cabana_env.Dir("../../opendbc/dbc").abspath)
cabana_env['CXXFLAGS'] += [opendbc_path]

# build assets
assets = "assets/assets.cc"
assets_src = "assets/assets.qrc"
rcc = os.path.join(qt5.BIN_DIR, "rcc")
cabana_env.Command(assets, assets_src, f"{rcc} $SOURCES -o $TARGET")
cabana_env.Depends(assets, Glob('/assets/*', exclude=[assets, assets_src, "assets/assets.o"]))

cabana_srcs = ['mainwin.cc', 'streams/pandastream.cc', 'streams/devicestream.cc', 'streams/livestream.cc', 'streams/abstractstream.cc', 'streams/replaystream.cc', 'binaryview.cc', 'historylog.cc', 'videowidget.cc', 'signalview.cc',
               'streams/routes.cc', 'dbc/dbc.cc', 'dbc/dbcfile.cc', 'dbc/dbcmanager.cc',
               'utils/export.cc', 'utils/util.cc', 'utils/elidedlabel.cc',
               'chart/chartswidget.cc', 'chart/chart.cc', 'chart/signalselector.cc', 'chart/tiplabel.cc', 'chart/sparkline.cc',
               'commands.cc', 'messageswidget.cc', 'streamselector.cc', 'settings.cc', 'panda.cc',
               'cameraview.cc', 'detailwidget.cc', 'tools/findsimilarbits.cc', 'tools/findsignal.cc', 'tools/routeinfo.cc']
if arch != "Darwin":
  cabana_srcs += ['streams/socketcanstream.cc']
cabana_lib = cabana_env.Library("cabana_lib", cabana_srcs, LIBS=cabana_libs, FRAMEWORKS=base_frameworks)
cabana_env.Program('_cabana', ['cabana.cc', cabana_lib, assets], LIBS=cabana_libs, FRAMEWORKS=base_frameworks)

if GetOption('extras'):
  cabana_env.Program('tests/test_cabana', ['tests/test_runner.cc', 'tests/test_cabana.cc', cabana_lib], LIBS=[cabana_libs])

output_json_file = 'tools/cabana/dbc/car_fingerprint_to_dbc.json'
generate_dbc = cabana_env.Command('#' + output_json_file,
                                  ['dbc/generate_dbc_json.py'],
                                  "python3 tools/cabana/dbc/generate_dbc_json.py --out " + output_json_file)
cabana_env.Depends(generate_dbc, ["#common", '#opendbc_repo', "#cereal", "#msgq_repo"])
